version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "installing"
  pre_build:
    commands:
      - echo "pre build"
  build:
    commands:
      - echo "building"
  post_build:
    commands:
      - echo "post build"
