version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - echo "installing"
      - npm install
  pre_build:
    commands:
      - echo "pre build"
      - npm run testc
  build:
    commands:
      - echo "building"
      - npm run build
  post_build:
    commands:
      - echo "post build"
      - aws s3 sync build/ s3:///pokemon-val-build-pipeline-bucket
artifacts:
  files:
    - build/**/*
